### ISSUE TITLE
i-pi + lammps problem

### ISSUE THREAD

**Issue by changxiaoju** [lab-cosmo/i-pi-dev_archive#244]
I do PIMD using i-pi with lammps.
I have 8 beads and 8 xyz position files, and all of them are very different from trajectory dumped by lammps. Is it normal?  Which trajectory should i believe?
Meanwhile, the thermo information dumped by lammps and i-pi are the same.
the 
i-pi input file:
` <trajectory filename='pos' stride='1000' format='xyz' cell_units='angstrom'> positions{angstrom} </trajectory>`
` <total_steps> 500000 </total_steps>`
lammps input file:
`variable        NSTEPS          equal 4000002`
`dump            trj all atom 10000 out.lammpstrj`

**Comment by ceriottm** [comment]
why are you using this ancient fork? move to `https://github.com/i-pi/i-pi` and if you still see a problem post a bug there. this repo is effectively read-only, nobody touched it in nearly 4 years.
